name: prod

on:
  workflow_run:
    workflows: ["Dev"]
    types:
      - completed

permissions:
  contents: read

jobs:
  deploy-to-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Prod deployment
        run: echo "Prod deployment"
    environment:
      name: 'Prod'
